# Generated by Django 2.2.4 on 2019-12-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_article_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
    ]
